### PR TITLE
Added English and Spanish translations

### PR DESCRIPTION
**Pull request by ordago**
Created the folders values-es and values-en and added the respective
strings.xml

### CODE REVIEW

**Comment by Kamshak** [comment]
Thanks, much appreciated! :+1:

**Comment by ordago** [comment]
You're welcome.

The translations were made based on the original file. I couldn't generate the apk with Android Studio to test them. Could you provide an apk to download? Thanks.

**Comment by Kamshak** [comment]
Sure, here you go: https://www.dropbox.com/s/q1myp8dxrqkig9h/app-release.apk?dl=0

**Comment by ordago** [comment]
Thanks.

**Pull request merged**
